language: c
sudo: true
dist: trusty

compiler:
    - gcc

#Build steps
before_script:
    - sudo apt-get install apitrace-gl-frontend imagemagick -y
    - mkdir build
    - cd build
    - cmake .. -DODROID=1

script:
    - make
    - cd ../tests
    - ./tests.sh ../lib
