language: c
sudo: true
dist: trusty

compiler:
    - gcc

#Build steps
before_script:
    - sudo apt-get install apitrace imagemagick -y
    - mkdir build
    - cd build
    - cmake .. -DODROID=1

stage: build
    script:
        - make

stage: test
    script:
        - cd ../tests
        - ./tests.sh ../lib
