language: c
sudo: true
#dist: xenial

compiler:
    - gcc

#Build steps
# apt-get is for regression testing and building apitrace
before_script:
    - sudo apt-get install apitrace imagemagick -y
    - mkdir build
    - cd build
    - cmake .. -DODROID=1

script:
    - make
    - cd ../tests
    - ./tests.sh ../lib
