language: c
sudo: true
dist: trusty

compiler:
    - gcc

#Build steps
before_script:
    - sudo apt-get install apitrace-gl-frontend imagemagick xvfb -y
    - mkdir build
    - cd build
    - cmake .. -DODROID=1

script:
    - make

after_script:
    - cd ../tests
    - Xvfb :1 &
    - DISPLAY=:1 ./tests.sh ../lib
